name: range_column_blog
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^28.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - Image\Canada.png
    - Image\France.png
    - Image\Germany.png
    - Image\Italy.png
    - Image\Japan.png
    - Image\UK.png
    - Image\USA.png